# 1. build stage
FROM node:20-alpine AS build

WORKDIR /app

COPY Frontend/package*.json ./
RUN npm ci

COPY Frontend/ .

RUN npm run build -- --configuration=production

# 2. nginx stage
FROM nginx:1.28-alpine

# Angular build → nginx web root
COPY --from=build /app/dist/new/browser/ /usr/share/nginx/html/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
