# ---- BUILD STAGE ----
FROM maven:3.9.6-eclipse-temurin-21 AS builder
WORKDIR /app

COPY Backend/pom.xml .
RUN mvn -q dependency:go-offline

COPY Backend/src ./src
RUN mvn -q package -DskipTests

# ---- RUN STAGE ----
FROM eclipse-temurin:21-jre
WORKDIR /app

COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8080
ENTRYPOINT [ "sh", "-c", "sleep 20 && java -jar app.jar" ]
